"""Export Utilities for LegalEase.

Generates in-memory TXT, DOCX, and PDF representations of legal documents.
Does not write to local temporary files to ensure full compatibility with
serverless environments (such as Vercel).
"""

import io
import re
from typing import Optional
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn
from fpdf import FPDF

# Branding & Disclaimer Constants
APP_NAME = "LegalEase"
BRAND_SUBTITLE = "AI-Powered Legal Document Generator"
DISCLAIMER_TEXT = (
    "For informational and drafting purposes only. "
    "Not legal advice. Review with qualified counsel before execution."
)

COLOR_PRIMARY_HEX = "0F172A"  # Deep Slate/Navy
COLOR_ACCENT_HEX = "C59B27"   # Warm Gold
COLOR_MUTED_HEX = "64748B"    # Slate 500


def export_to_txt(content: str) -> io.BytesIO:
    """Export legal document as a clean UTF-8 plain text file buffer."""
    header = (
        f"======================================================================\n"
        f"{APP_NAME} — {BRAND_SUBTITLE}\n"
        f"LEGAL DISCLAIMER: {DISCLAIMER_TEXT}\n"
        f"======================================================================\n\n"
    )
    full_text = header + content.strip() + "\n"
    buffer = io.BytesIO(full_text.encode("utf-8"))
    buffer.seek(0)
    return buffer


def _set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    """Set inner padding margins for a docx table cell."""
    tcPr = cell._tc.get_or_add_tcPr()
    tcMar = OxmlElement('w:tcMar')
    for margin_name, val in [('top', top), ('bottom', bottom), ('left', left), ('right', right)]:
        node = OxmlElement(f'w:{margin_name}')
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tcMar.append(node)
    tcPr.append(tcMar)


def export_to_docx(content: str, document_title: str = "Legal Document") -> io.BytesIO:
    """Export legal document to a beautifully formatted DOCX file buffer.

    Requirements:
    - Times New Roman font throughout
    - Professional heading hierarchy
    - Numbered sections
    - 1-inch margins
    - Header & Footer with LegalEase branding and disclaimer
    - Page numbers
    - Formatted signature blocks
    - In-memory BytesIO buffer (serverless safe)
    """
    doc = Document()

    # 1. Page Margins (1 inch all around)
    for section in doc.sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)
        section.page_width = Inches(8.5)
        section.page_height = Inches(11.0)

        # 2. Header
        header = section.header
        header_p = header.paragraphs[0]
        header_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        h_run = header_p.add_run(f"{APP_NAME} | {document_title} (Draft)")
        h_run.font.name = "Times New Roman"
        h_run.font.size = Pt(8.5)
        h_run.font.italic = True
        h_run.font.color.rgb = RGBColor(100, 116, 139)

        # 3. Footer with disclaimer and branding
        footer = section.footer
        footer_p = footer.paragraphs[0]
        footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        f_run = footer_p.add_run(
            f"Generated by {APP_NAME} — {DISCLAIMER_TEXT}"
        )
        f_run.font.name = "Times New Roman"
        f_run.font.size = Pt(8.0)
        f_run.font.italic = True
        f_run.font.color.rgb = RGBColor(120, 120, 120)

    # Base Normal Style setup
    normal_style = doc.styles['Normal']
    normal_style.font.name = 'Times New Roman'
    normal_style.font.size = Pt(11)
    normal_style.font.color.rgb = RGBColor(15, 23, 42)

    lines = content.strip().split("\n")
    in_signature_block = False
    signature_lines = []

    # Regex patterns for parsing document structure
    heading_pattern = re.compile(r'^(?:[0-9]+\.|\bSECTION\b|\bARTICLE\b|\bCLAUSE\b)\s+([A-Z\s]{3,}|.+)$', re.IGNORECASE)
    subheading_pattern = re.compile(r'^[0-9]+\.[0-9]+(?:\.[0-9]+)?\s+(.+)$')
    title_pattern = re.compile(r'^[A-Z0-9\s,\-\(\)]{4,}$')

    is_first_line = True

    for raw_line in lines:
        line = raw_line.strip()

        # Handle empty lines
        if not line:
            if in_signature_block and signature_lines:
                _render_signature_table_docx(doc, signature_lines)
                signature_lines = []
                in_signature_block = False
            continue

        # Check for signature section marker
        if re.search(r'^\s*(?:IN WITNESS WHEREOF|SIGNATURES?|EXECUTED AS AN AGREEMENT)\b', line, re.IGNORECASE):
            in_signature_block = True
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(18)
            p.paragraph_format.space_after = Pt(8)
            p.paragraph_format.keep_with_next = True
            run = p.add_run(line.upper())
            run.bold = True
            run.font.name = "Times New Roman"
            run.font.size = Pt(12)
            run.font.color.rgb = RGBColor(15, 23, 42)
            continue

        if in_signature_block:
            signature_lines.append(line)
            continue

        # Document Title (first non-empty line or explicit uppercase title)
        if is_first_line and (title_pattern.match(line) or len(line) < 100):
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            p.paragraph_format.space_before = Pt(12)
            p.paragraph_format.space_after = Pt(14)
            p.paragraph_format.keep_with_next = True
            run = p.add_run(line.upper())
            run.bold = True
            run.font.name = "Times New Roman"
            run.font.size = Pt(15)
            run.font.color.rgb = RGBColor(15, 23, 42)
            is_first_line = False
            continue

        is_first_line = False

        # Section Headings (e.g. "1. DEFINITIONS", "SECTION 2 - OBLIGATIONS")
        if heading_pattern.match(line):
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(14)
            p.paragraph_format.space_after = Pt(4)
            p.paragraph_format.keep_with_next = True
            run = p.add_run(line)
            run.bold = True
            run.font.name = "Times New Roman"
            run.font.size = Pt(12.5)
            run.font.color.rgb = RGBColor(15, 23, 42)
            continue

        # Sub-clauses (e.g. "1.1 Confidential Information")
        if subheading_pattern.match(line):
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(8)
            p.paragraph_format.space_after = Pt(3)
            p.paragraph_format.keep_with_next = True
            run = p.add_run(line)
            run.bold = True
            run.font.name = "Times New Roman"
            run.font.size = Pt(11)
            run.font.color.rgb = RGBColor(30, 41, 59)
            continue

        # Regular Body Paragraph
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(2)
        p.paragraph_format.space_after = Pt(6)
        p.paragraph_format.line_spacing = 1.15
        
        # Highlight placeholders in bold or distinctive styling
        _add_formatted_runs_docx(p, line)

    # Flush remaining signature lines if any
    if in_signature_block and signature_lines:
        _render_signature_table_docx(doc, signature_lines)

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer


def _add_formatted_runs_docx(paragraph, line: str):
    """Add runs to paragraph, formatting [PLACEHOLDER] text cleanly."""
    parts = re.split(r'(\[[A-Z0-9\s_\-\/]+\])', line)
    for part in parts:
        if not part:
            continue
        run = paragraph.add_run(part)
        run.font.name = "Times New Roman"
        run.font.size = Pt(11)
        if part.startswith('[') and part.endswith(']'):
            run.bold = True
            run.font.color.rgb = RGBColor(180, 83, 9)  # Amber / Dark Gold for placeholders
        else:
            run.font.color.rgb = RGBColor(15, 23, 42)


def _render_signature_table_docx(doc: Document, lines: list):
    """Render a clean 2-column signature block in docx."""
    table = doc.add_table(rows=1, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False

    # Divide lines between Party A and Party B or render as structured boxes
    col_a_text = []
    col_b_text = []

    current_col = col_a_text
    for l in lines:
        if re.search(r'\b(?:PARTY B|SECOND PARTY|EMPLOYEE|CONTRACTOR|BUYER|TENANT)\b', l, re.IGNORECASE):
            current_col = col_b_text
        current_col.append(l)

    if not col_b_text and len(col_a_text) > 4:
        # Split half-half if no clear delimiter
        mid = len(col_a_text) // 2
        col_b_text = col_a_text[mid:]
        col_a_text = col_a_text[:mid]

    cell_a = table.cell(0, 0)
    cell_b = table.cell(0, 1)

    cell_a.width = Inches(3.2)
    cell_b.width = Inches(3.2)
    _set_cell_margins(cell_a, top=140, bottom=140, left=140, right=140)
    _set_cell_margins(cell_b, top=140, bottom=140, left=140, right=140)

    p_a = cell_a.paragraphs[0]
    p_a.paragraph_format.line_spacing = 1.2
    for l in (col_a_text or ["PARTY A:", "", "Signature: ___________________", "Name: ______________________", "Date: ______________________"]):
        run = p_a.add_run(l + "\n")
        run.font.name = "Times New Roman"
        run.font.size = Pt(10)

    p_b = cell_b.paragraphs[0]
    p_b.paragraph_format.line_spacing = 1.2
    for l in (col_b_text or ["PARTY B:", "", "Signature: ___________________", "Name: ______________________", "Date: ______________________"]):
        run = p_b.add_run(l + "\n")
        run.font.name = "Times New Roman"
        run.font.size = Pt(10)


def _sanitize_pdf_text(text: str) -> str:
    """Replace non-latin-1 unicode characters with readable ascii equivalents."""
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2014": " -- ",
        "\u2013": "-",
        "\u2026": "...",
        "\u2022": "*",
        "\u00a0": " ",
        "\u2122": "(TM)",
        "\u00ae": "(R)",
        "\u00a9": "(C)",
        "\u20ac": "EUR",
        "\u00a3": "GBP",
    }
    for orig, repl in replacements.items():
        text = text.replace(orig, repl)
    # Encode to latin-1, replacing any remaining incompatible characters
    return text.encode("latin-1", "replace").decode("latin-1")


class LegalEasePDF(FPDF):
    """Custom FPDF2 subclass for professional legal document rendering."""

    def __init__(self, doc_title: str = "Legal Document"):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.doc_title = _sanitize_pdf_text(doc_title)
        self.set_margins(left=20, top=22, right=20)
        self.set_auto_page_break(auto=True, margin=22)

    def header(self):
        # Subtle header rule and title on subsequent pages
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 8, f"{APP_NAME} | {self.doc_title} (Draft)", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(226, 232, 240)
        self.set_line_width(0.3)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-18)
        self.set_draw_color(226, 232, 240)
        self.set_line_width(0.3)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(2)

        self.set_font("Helvetica", "I", 7.5)
        self.set_text_color(100, 116, 139)
        # Left: Disclaimer; Right: Page number
        disclaimer_clean = _sanitize_pdf_text(DISCLAIMER_TEXT)
        self.cell(130, 6, f"Generated by {APP_NAME} - {disclaimer_clean}", align="L")
        self.cell(40, 6, f"Page {self.page_no()}/{{nb}}", align="R")


def export_to_pdf(content: str, document_title: str = "Legal Document") -> io.BytesIO:
    """Export legal document as a high-quality PDF file buffer.

    Requirements:
    - Clean typography (Helvetica / Times)
    - LegalEase header and page numbers
    - Numbered sections
    - Support for multi-page documents
    - Signature blocks
    - In-memory BytesIO buffer
    """
    pdf = LegalEasePDF(doc_title=document_title)
    pdf.alias_nb_pages()
    pdf.add_page()

    lines = content.strip().split("\n")
    heading_pattern = re.compile(r'^(?:[0-9]+\.|\bSECTION\b|\bARTICLE\b|\bCLAUSE\b)\s+([A-Z\s]{3,}|.+)$', re.IGNORECASE)
    subheading_pattern = re.compile(r'^[0-9]+\.[0-9]+(?:\.[0-9]+)?\s+(.+)$')
    title_pattern = re.compile(r'^[A-Z0-9\s,\-\(\)]{4,}$')

    is_first_line = True
    in_signature_block = False

    for raw_line in lines:
        line = _sanitize_pdf_text(raw_line.strip())

        if not line:
            pdf.ln(3)
            continue

        # Signature marker
        if re.search(r'^\s*(?:IN WITNESS WHEREOF|SIGNATURES?|EXECUTED AS AN AGREEMENT)\b', line, re.IGNORECASE):
            in_signature_block = True
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(0, 8, line.upper(), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
            continue

        if in_signature_block:
            pdf.set_font("Helvetica", "", 9.5)
            pdf.set_text_color(30, 41, 59)
            pdf.cell(0, 5, line, new_x="LMARGIN", new_y="NEXT")
            continue

        # Title formatting
        if is_first_line and (title_pattern.match(line) or len(line) < 100):
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(0, 10, line.upper(), align="C", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(4)
            is_first_line = False
            continue

        is_first_line = False

        # Section Headings (e.g. 1. DEFINITIONS)
        if heading_pattern.match(line):
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 11.5)
            pdf.set_text_color(15, 23, 42)
            pdf.multi_cell(0, 6, line)
            pdf.ln(1)
            continue

        # Sub-clauses (e.g. 1.1 Scope)
        if subheading_pattern.match(line):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 41, 59)
            pdf.multi_cell(0, 5.5, line)
            continue

        # Body paragraph
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 41, 59)
        pdf.multi_cell(0, 5.2, line)
        pdf.ln(1.5)

    buffer = io.BytesIO()
    pdf_bytes = pdf.output()
    buffer.write(pdf_bytes)
    buffer.seek(0)
    return buffer
